name: Codespace
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: action/setup-python@v1
      with: 
        python-version: 3.8
    - name: Install Depedencies
      run:
        make install
